// UAP Report Atlas — case data
// Compiled from AARO's Historical Record Report Vol. I, AARO FY22–FY25 annual
// reports to Congress, AARO individual case-resolution reports, congressional
// UAP hearing testimony (2023–2025), and corroborating news coverage.
// STATUS values mirror AARO's own classification language:
//   unresolved      — reviewed, no explanation reached
//   explained        — AARO/USG reached a prosaic explanation (balloon, drone, satellite, etc.)
//   uncorroborated   — insufficient evidence to assess either way
// PRECISION: "exact" = a named, specific site; "approx" = illustrative placement
// within a named region because no precise site was publicly disclosed.

const CASES = [
  { id:"tictac", name:"“Tic Tac” / FLIR1", date:"2004-11-14", lat:32.75, lon:-118.05, location:"Pacific Ocean, ~100mi SW of San Diego, CA", precision:"approx", status:"unresolved", agency:"U.S. Navy", summary:"Navy F/A-18 pilots intercepted a white, oblong object near the USS Nimitz strike group. The Navy confirmed the footage as authentic in 2019; AARO still lists the case unresolved.", source:"Navy (2019 confirmation); AARO" },
  { id:"gimbal", name:"“Gimbal”", date:"2015", lat:30.3, lon:-79.9, location:"Atlantic Ocean, off the U.S. East Coast", precision:"approx", status:"unresolved", agency:"U.S. Navy", summary:"Cockpit sensor footage shows a rotating, gimbal-shaped object recorded during a Navy training flight. Confirmed as authentic Navy footage in 2019.", source:"Navy (2019 confirmation); AARO" },
  { id:"gofast", name:"“GoFast”", date:"2015", lat:26.9, lon:-80.3, location:"Atlantic Ocean, off Florida", precision:"approx", status:"unresolved", agency:"U.S. Navy", summary:"Infrared footage of a small object skimming low over open water. AARO's 2023 technical review attributed its apparent high speed to a parallax effect.", source:"AARO technical review, 2023" },
  { id:"aguadilla", name:"Aguadilla Encounter", date:"2013-04-25", lat:18.43, lon:-67.15, location:"Aguadilla, Puerto Rico", precision:"exact", status:"explained", agency:"DHS / Customs and Border Protection", summary:"A CBP surveillance aircraft recorded objects appearing to enter and exit the ocean. AARO assessed the footage as a parallax illusion involving slow-moving or stationary balloons.", source:"AARO Case Resolution Report" },
  { id:"malmstrom", name:"Echo Flight Shutdown", date:"1967-03-16", lat:47.51, lon:-111.19, location:"Malmstrom AFB, Montana", precision:"exact", status:"uncorroborated", agency:"U.S. Air Force / Strategic Air Command", summary:"Ten Minuteman ICBMs at Echo Flight briefly dropped offline during a reported UAP sighting near the launch complex, per declassified Air Force records and a former launch officer's testimony.", source:"Declassified USAF records; R. Salas testimony" },
  { id:"rendlesham", name:"Rendlesham Forest Incident", date:"1980-12-26", lat:52.09, lon:1.44, location:"Rendlesham Forest, Suffolk, England", precision:"exact", status:"unresolved", agency:"U.S. Air Force (RAF Woodbridge)", summary:"USAF security personnel reported lights and an apparent landed craft near the base perimeter over several nights, documented in the deputy base commander's contemporaneous memo.", source:"Halt memo; USAF personnel accounts" },
  { id:"lakehuron", name:"Lake Huron Intercept", date:"2023-02-12", lat:44.4, lon:-82.4, location:"Over Lake Huron, near the U.S.–Canada border", precision:"approx", status:"unresolved", agency:"U.S. Air National Guard / NORAD", summary:"An F-16 shot down an unidentified octagonal object over the lake; debris was never recovered.", source:"NORAD; Washington Post" },
  { id:"fortbelvoir", name:"Fort Belvoir Ring Object", date:"1957-09", lat:38.7126, lon:-77.1466, location:"Fort Belvoir, Virginia", precision:"exact", status:"uncorroborated", agency:"U.S. Army", summary:"An Army private photographed a large, non-reflective black ring approaching the base before it dispersed into a cloud — one of the earliest documented sightings on a U.S. Army installation.", source:"Contemporary photo series; UFO historical archives" },
  { id:"socorro", name:"Socorro / White Sands Landing", date:"1964-04-24", lat:34.0584, lon:-106.8914, location:"Socorro, NM, adjacent to White Sands Missile Range", precision:"exact", status:"unresolved", agency:"U.S. Army (White Sands Missile Range) / USAF Project Blue Book", summary:"A police officer reported a landed craft and two figures just outside the Army's White Sands range. Project Blue Book listed it “unknown” — widely regarded as one of the best-documented close encounters on record.", source:"Project Blue Book; Army investigation notes" },

  { id:"la1942", name:"Battle of Los Angeles", date:"1942-02-24", lat:33.94, lon:-118.41, location:"Los Angeles, California", precision:"exact", status:"explained", agency:"U.S. Army / Army Air Forces", summary:"Coastal anti-aircraft batteries fired over 1,400 rounds at an unidentified aerial target during a wartime false alarm, later attributed to “war nerves” and a stray weather balloon.", source:"U.S. Army after-action review" },
  { id:"mantell", name:"Mantell UFO Incident", date:"1948-01-07", lat:36.87, lon:-86.57, location:"Near Franklin, Kentucky (Fort Knox area)", precision:"exact", status:"explained", agency:"USAF / Kentucky Air National Guard", summary:"Capt. Thomas Mantell died after his F-51 crashed while pursuing an object; Project Blue Book attributed the object to a Skyhook balloon.", source:"Project Blue Book" },
  { id:"chileswhitted", name:"Chiles–Whitted UFO Encounter", date:"1948-07-24", lat:32.38, lon:-86.30, location:"Near Montgomery, Alabama", precision:"approx", status:"unresolved", agency:"Eastern Air Lines / USAF Project Sign", summary:"Two airline pilots reported a near-collision with a large, cigar-shaped, windowed craft with flame exhaust. The Air Force investigation report was later destroyed.", source:"Project Sign case file (destroyed); pilot accounts" },
  { id:"gorman", name:"Gorman Dogfight", date:"1948-10-01", lat:46.88, lon:-96.79, location:"Fargo, North Dakota", precision:"exact", status:"explained", agency:"North Dakota Air National Guard / USAF", summary:"Pilot George Gorman engaged in a 27-minute aerial “dogfight” with a maneuvering light, officially attributed to a lighted weather balloon.", source:"Project Sign / Blue Book" },
  { id:"lubbock", name:"Lubbock Lights", date:"1951-08-25", lat:33.58, lon:-101.85, location:"Lubbock, Texas", precision:"exact", status:"unresolved", agency:"USAF Project Grudge / Blue Book", summary:"Texas Tech professors and residents observed a V-shaped formation of lights on multiple nights, photographed by a student; the radar-associated sighting remains listed as unidentified.", source:"Project Blue Book" },
  { id:"dcflap", name:"1952 Washington, D.C. UFO Incident", date:"1952-07-19", lat:38.85, lon:-77.04, location:"Washington, D.C. (National Airport airspace)", precision:"exact", status:"explained", agency:"USAF / Civil Aeronautics Administration", summary:"Radar operators at two facilities tracked multiple unidentified, slow-moving targets over restricted airspace near the White House; the Air Force attributed the returns to a temperature inversion.", source:"USAF investigation; CIA Robertson Panel" },
  { id:"rb47", name:"RB-47 UFO Encounter", date:"1957-07-17", lat:30.0, lon:-90.0, location:"Gulf Coast region (MS/LA/TX/OK, in-flight)", precision:"approx", status:"unresolved", agency:"USAF Strategic Air Command", summary:"A reconnaissance aircrew tracked an object visually, on airborne electronic countermeasures gear, and on ground radar simultaneously for over 700 miles and 90 minutes.", source:"USAF crew debrief; Project Blue Book" },
  { id:"levelland", name:"Levelland UFO Case", date:"1957-11-02", lat:33.59, lon:-102.38, location:"Levelland, Texas", precision:"exact", status:"explained", agency:"USAF Project Blue Book / local police", summary:"Multiple independent motorists reported engine and headlight failure near a glowing, egg-shaped object on rural highways; the Air Force attributed it to ball lightning or an electrical storm.", source:"Project Blue Book" },
  { id:"trindade", name:"Trindade Island Photographs", date:"1958-01-16", lat:-20.51, lon:-29.32, location:"Trindade Island, Brazil (South Atlantic)", precision:"exact", status:"uncorroborated", agency:"Brazilian Navy", summary:"A civilian photographer aboard a Brazilian Navy research vessel captured a sequence of images of a ring-shaped object, witnessed by dozens of sailors.", source:"Brazilian Navy inquiry" },
  { id:"kecksburg", name:"Kecksburg UFO Incident", date:"1965-12-09", lat:40.17, lon:-79.46, location:"Kecksburg, Pennsylvania", precision:"exact", status:"explained", agency:"USAF / NASA", summary:"A fireball seen over several states reportedly crashed in nearby woods; witnesses described a military recovery of an acorn-shaped object. Officially attributed to a meteor.", source:"USAF / NASA statements" },
  { id:"minot1968", name:"Minot AFB UFO Incident", date:"1968-10-24", lat:48.42, lon:-101.35, location:"Minot AFB, North Dakota", precision:"exact", status:"unresolved", agency:"USAF / Strategic Air Command", summary:"Missile-site security personnel and a B-52 bomber crew tracked an object visually and on radar near Minuteman launch facilities; the SAC investigation reached no conclusion.", source:"USAF/SAC incident report" },
  { id:"coyne", name:"Coyne Helicopter Incident", date:"1973-10-18", lat:40.76, lon:-82.52, location:"Near Mansfield, Ohio (Charles Mill Lake)", precision:"exact", status:"unresolved", agency:"U.S. Army Reserve", summary:"An Army Reserve helicopter crew reported a near-collision with a silent, cigar-shaped craft that caused instrument anomalies and briefly forced the aircraft into an uncontrolled descent.", source:"Center for UFO Studies; crew accounts" },
  { id:"loring", name:"Loring AFB UFO Incursions", date:"1975-10-27", lat:46.95, lon:-67.88, location:"Loring AFB, Limestone, Maine", precision:"exact", status:"unresolved", agency:"USAF / Strategic Air Command", summary:"Security personnel and pilots reported a low-flying, silent, maneuverable object repeatedly circling the nuclear weapons storage area over consecutive nights.", source:"Declassified NMCC memoranda" },
  { id:"wurtsmith", name:"Wurtsmith AFB UFO Incursion", date:"1975-10-30", lat:44.45, lon:-83.39, location:"Wurtsmith AFB, Oscoda, Michigan", precision:"exact", status:"unresolved", agency:"USAF / Strategic Air Command", summary:"Security police reported an unlit, helicopter-like object hovering over the weapons storage area; a KC-135 crew obtained radar and visual contact before it outran them.", source:"NORAD/SAC incident logs" },
  { id:"tehran1976", name:"1976 Tehran UFO Incident", date:"1976-09-19", lat:35.69, lon:51.39, location:"Tehran, Iran", precision:"exact", status:"unresolved", agency:"Imperial Iranian Air Force / U.S. DIA", summary:"Two F-4 Phantom interceptors independently lost instrumentation and weapons systems as they approached a bright, maneuvering object, documented in a widely-cited declassified DIA report.", source:"Declassified DIA report" },
  { id:"jal1628", name:"Japan Air Lines Flight 1628 Incident", date:"1986-11-17", lat:64.0, lon:-145.0, location:"Airspace over eastern/central Alaska", precision:"approx", status:"unresolved", agency:"Federal Aviation Administration", summary:"A JAL 747 cargo crew reported being paced by lighted objects for about 30 minutes, partially corroborated by ground radar; the FAA investigation was inconclusive.", source:"FAA investigation report" },
  { id:"belgium", name:"Belgian UFO Wave / F-16 Intercept", date:"1990-03-30", lat:50.63, lon:6.03, location:"Eupen, Belgium", precision:"exact", status:"unresolved", agency:"Belgian Air Force / Gendarmerie", summary:"Amid a wave of thousands of witness reports of large, silent triangular craft, Belgian F-16s achieved four radar locks on an object exhibiting extreme accelerations before losing contact.", source:"Belgian Air Force / SOBEPS report" },

  { id:"roswell", name:"Roswell Incident", date:"1947-07", lat:33.39, lon:-104.52, location:"Roswell, New Mexico", precision:"exact", status:"explained", agency:"U.S. Army Air Forces", summary:"AARO's historical review traced recovered debris to a Project Mogul high-altitude balloon train, finding no evidence of alien bodies or a recovered craft.", source:"AARO Historical Record Report Vol. I" },
  { id:"arnold", name:"Kenneth Arnold Sighting", date:"1947-06-24", lat:46.85, lon:-121.76, location:"Mount Rainier area, Washington State", precision:"exact", status:"uncorroborated", agency:"Civilian pilot (reviewed by USG)", summary:"A private pilot's report of nine crescent-shaped objects near Mount Rainier coined the term “flying saucer” and is cited by AARO as the origin point of the modern UFO reporting era.", source:"AARO Historical Record Report Vol. I" },
  { id:"foofighters", name:"“Foo Fighter” Sightings", date:"1944", lat:49.0, lon:10.0, location:"European theater, WWII (regional)", precision:"approx", status:"uncorroborated", agency:"U.S. Army Air Forces", summary:"Aircrews repeatedly reported small, fast balls of light pacing their aircraft. AARO's historical report calls it the most high-profile UAP-type phenomenon of the WWII era.", source:"AARO Historical Record Report Vol. I" },
  { id:"greenfireballs", name:"Green Fireballs (Project Twinkle)", date:"1948-12", lat:35.88, lon:-106.30, location:"Los Alamos / Sandia / Kirtland region, New Mexico", precision:"approx", status:"unresolved", agency:"U.S. Army / Atomic Energy Commission", summary:"Waves of green fireball sightings near nuclear-weapons sites prompted a dedicated study; a 1949 scientific panel including Edward Teller reached no consensus explanation.", source:"AARO Historical Record Report Vol. I" },
  { id:"aawsap", name:"AAWSAP/BAASS Utah Investigation", date:"2008", lat:40.25, lon:-109.89, location:"Private ranch property, Utah (approximate)", precision:"approx", status:"uncorroborated", agency:"DIA-funded contractor (BAASS)", summary:"A Defense Intelligence Agency-funded program investigated claims of anomalous activity at a Utah ranch property; AARO's review found the claims unsubstantiated and outside the program's legitimate scope.", source:"AARO Historical Record Report Vol. I" },
  { id:"icbmclaims", name:"ICBM Site UAP Claims", date:"1966", lat:44.14, lon:-103.10, location:"Ellsworth AFB, South Dakota (related claims also at Vandenberg AFB, CA and Minot AFB, ND)", precision:"approx", status:"uncorroborated", agency:"U.S. Air Force", summary:"Former missile-site personnel described UAP disrupting launch control power, and one claimed video of a UAP destroying a test ICBM mid-flight; AARO found no corroborating evidence.", source:"AARO Historical Record Report Vol. I" },
  { id:"konablue", name:"“KONA BLUE” Program Claim", date:"2021", lat:38.91, lon:-77.02, location:"Washington, D.C. (Department of Homeland Security)", precision:"exact", status:"explained", agency:"Department of Homeland Security", summary:"A whistleblower alleged a secret DHS program concealed non-human biologics. AARO's review found no such program ever existed.", source:"AARO Historical Record Report Vol. I" },
  { id:"tremonton", name:"Tremonton, Utah UFO Film", date:"1952-07-02", lat:41.71, lon:-112.30, location:"Tremonton, Utah", precision:"exact", status:"uncorroborated", agency:"U.S. Navy", summary:"A Navy officer's color film of bright, moving objects was analyzed by Naval photo-interpreters, who concluded the lights were not birds, balloons, or aircraft.", source:"Naval Photographic Interpretation Center memo" },
  { id:"greatfalls", name:"Great Falls, Montana UFO Film", date:"1950-08-15", lat:47.50, lon:-111.30, location:"Great Falls, Montana", precision:"exact", status:"uncorroborated", agency:"U.S. Navy", summary:"A civilian's film of two bright, moving objects was analyzed alongside the Tremonton footage in a Navy memorandum re-reviewed by AARO.", source:"Naval Photographic Interpretation Center memo" },

  { id:"southeastasia", name:"Southeast Asia Triangles", date:"2017", lat:12.0, lon:114.0, location:"South China Sea (regional)", precision:"approx", status:"explained", agency:"Department of Defense / AARO", summary:"Triangle-shaped objects seen in surveillance imagery were assessed as almost certainly cone-shaped fishing nets floating on the ocean surface.", source:"AARO Case Resolution Report" },
  { id:"altaqaddum", name:"Al Taqaddum “Jellyfish” Object", date:"2017-10-23", lat:33.34, lon:43.57, location:"Al Taqaddum Air Base, Iraq", precision:"exact", status:"explained", agency:"U.S. military aerostat sensor", summary:"A 17-minute infrared video of a glowing, jellyfish-like object was assessed with high confidence to be a cluster of fully or partially inflated balloons.", source:"AARO Case Resolution Report" },
  { id:"etna", name:"Mount Etna Object", date:"2018-12", lat:37.75, lon:15.00, location:"Mount Etna, Sicily, Italy", precision:"exact", status:"explained", agency:"DoD / AARO (NAS Sigonella)", summary:"Sensor video appeared to show an object passing through Etna's eruption plume unaffected; AARO attributed it to a wind-borne balloon with atmospheric distortion.", source:"AARO Case Resolution Report" },
  { id:"eglin", name:"Eglin UAP", date:"2023-01-26", lat:30.48, lon:-86.53, location:"Near Eglin Air Force Base, Florida", precision:"exact", status:"explained", agency:"USAF pilot report", summary:"A formation of four objects seen by a military pilot at 16,000 feet was assessed, with moderate confidence, as a large commercial lighting balloon.", source:"AARO Case Resolution Report" },
  { id:"harare", name:"Harare Airport Disc", date:"2008-07-02", lat:-17.93, lon:31.09, location:"Harare International Airport, Zimbabwe", precision:"exact", status:"uncorroborated", agency:"CIA (foreign reporting)", summary:"A disc-shaped object with rotating underside lights was reported hovering over the airport, prompting an internal CIA cable and debate over its origin.", source:"Declassified CIA cable" },

  { id:"ussomaha", name:"USS Omaha Transmedium Encounter", date:"2019-07-15", lat:32.5, lon:-117.5, location:"Offshore San Diego, California", precision:"approx", status:"unresolved", agency:"U.S. Navy", summary:"Radar and infrared sensors aboard USS Omaha tracked a spherical object that appeared to descend into the ocean, with no wreckage recovered.", source:"Navy incident report; congressional testimony" },
  { id:"destroyerswarm", name:"2019 Navy Destroyer Drone Swarm", date:"2019-07", lat:33.9, lon:-119.5, location:"Off Southern California, near the Channel Islands", precision:"approx", status:"uncorroborated", agency:"U.S. Navy (multiple destroyers)", summary:"Formations of drone-like and pyramid-shaped objects shadowed a Navy strike group over several nights; the source of the objects was never identified.", source:"Navy incident reports; sailor video" },
  { id:"cubeinsphere", name:"“Cube-in-Sphere” Virginia Beach Encounters", date:"2014", lat:36.85, lon:-75.5, location:"Warning Area W-72, off Virginia Beach, Virginia", precision:"approx", status:"unresolved", agency:"U.S. Navy (VFA-11)", summary:"Navy pilots repeatedly encountered a dark cube inside a transparent sphere, once passing within 50 feet of an aircraft, according to congressional testimony.", source:"Lt. Ryan Graves congressional testimony" },
  { id:"trstrikegroup", name:"Theodore Roosevelt Strike Group Near-Midairs", date:"2015-01", lat:36.5, lon:-75.0, location:"Offshore U.S. East Coast (Virginia/North Carolina)", precision:"approx", status:"unresolved", agency:"U.S. Navy", summary:"Navy leadership circulated an internal warning after multiple reported near-midair collisions between F/A-18s and UAP, per a rear admiral's congressional testimony.", source:"Rear Adm. Tim Gallaudet testimony" },
  { id:"vandenberg", name:"Vandenberg AFB UAP Cluster", date:"2003", lat:34.73, lon:-120.57, location:"Vandenberg Air Force Base, California", precision:"exact", status:"unresolved", agency:"USAF Security Forces", summary:"A former security officer testified to five distinct UAP incursions near missile-defense facilities between 2003 and 2005, witnessed by multiple personnel.", source:"J. Nuccetelli congressional testimony" },
  { id:"elbosque", name:"El Bosque Chilean Navy FLIR UAP", date:"2014-11-11", lat:-33.0, lon:-71.6, location:"Coastal airspace between San Antonio and Quintero, Chile", precision:"exact", status:"unresolved", agency:"Chilean Navy / CEFAA", summary:"A Navy helicopter's infrared camera recorded an elongated object with unexplained thermal discharges; a two-year government investigation could not identify it.", source:"Chilean Navy / CEFAA investigation" },
  { id:"ussjackson", name:"USS Jackson Tic-Tac Cluster", date:"2023", lat:21.0, lon:-158.0, location:"At sea, Pacific (vessel location approximate)", precision:"approx", status:"uncorroborated", agency:"U.S. Navy", summary:"An active-duty sailor testified to four Tic-Tac-shaped objects surfacing, linking up, and vanishing with synchronized acceleration.", source:"Senior Chief A. Wiggins congressional testimony" },
  { id:"chinaballoon", name:"Chinese High-Altitude Balloon", date:"2023-02-04", lat:33.7, lon:-78.9, location:"Off Myrtle Beach, South Carolina (shootdown site)", precision:"exact", status:"explained", agency:"USAF / U.S. Navy", summary:"A PRC surveillance balloon crossed the continental U.S. for over a week before being shot down, triggering a wave of congressional scrutiny of unidentified airspace objects.", source:"DoD statements; NORAD" },

  { id:"alaskaobj", name:"Alaska High-Altitude Object Shootdown", date:"2023-02-10", lat:70.0, lon:-149.0, location:"Beaufort Sea, off northern Alaska", precision:"approx", status:"unresolved", agency:"USAF / NORAD", summary:"An F-22 downed a small, cylindrical object near the Arctic Circle after it was deemed a flight hazard; no wreckage was ever recovered.", source:"NORAD; White House briefing" },
  { id:"yukonobj", name:"Yukon High-Altitude Object Shootdown", date:"2023-02-11", lat:63.0, lon:-136.0, location:"Yukon Territory, Canada", precision:"approx", status:"unresolved", agency:"NORAD / USAF", summary:"A cylindrical object was downed over remote terrain at Canada's request; debris was never recovered due to weather and terrain.", source:"NORAD; Government of Canada statement" },
  { id:"deirezzor", name:"Deir ez-Zor Metallic Orb", date:"2022-07-12", lat:35.34, lon:40.14, location:"Deir ez-Zor, Syria", precision:"exact", status:"uncorroborated", agency:"USAF (MQ-9 Reaper)", summary:"A drone filmed a small, metallic sphere with no visible means of propulsion; AARO later cited the case as representative of roughly 650 similarly-shaped reports.", source:"AARO briefing to Congress, April 2023" },
  { id:"southasia", name:"South Asia MQ-9 Disk Object", date:"2023-01-23", lat:24.0, lon:68.0, location:"South Asia (specific country undisclosed)", precision:"approx", status:"explained", agency:"USAF (MQ-9 Reaper)", summary:"A disk-like object tracked near a Reaper drone was publicly presented by AARO's director as resolved: a distant commuter aircraft.", source:"AARO director, Senate Armed Services briefing" },
  { id:"yemenorb", name:"Yemen Coast Orb / Hellfire Engagement", date:"2024-10-30", lat:14.5, lon:49.0, location:"Off the coast of Yemen", precision:"approx", status:"unresolved", agency:"U.S. military (MQ-9 drones)", summary:"A second drone fired a Hellfire missile at an unidentified, tracked orb; the footage was shown publicly at a 2025 House UAP hearing.", source:"House Oversight UAP hearing, 2025" },
  { id:"langleyswarm", name:"Langley AFB Drone Swarm", date:"2023-12-06", lat:37.08, lon:-76.36, location:"Joint Base Langley-Eustis, Hampton Roads, Virginia", precision:"exact", status:"unresolved", agency:"USAF / FBI / AARO", summary:"Groups of a dozen or more drones repeatedly overflew the base nightly for about 17 days, prompting officials to reposition aircraft; their source was never determined.", source:"USAF/FBI joint statement" },
  { id:"langleytriangle", name:"Langley AFB Triangle", date:"2021", lat:37.08, lon:-76.36, location:"Langley Air Force Base, Virginia", precision:"exact", status:"uncorroborated", agency:"U.S. Air Force", summary:"A veteran testified to Congress about a large, triangular craft with lava-like plasma hovering over the base before rapidly ascending out of sight.", source:"D. Borland congressional testimony, 2025" },
  { id:"njdrones", name:"New Jersey / Tri-State Drone Sightings", date:"2024-11", lat:40.22, lon:-74.52, location:"New Jersey (spreading to NY/PA), regional", precision:"approx", status:"explained", agency:"FBI / DHS", summary:"Thousands of nighttime drone reports prompted a federal task force; most were traced to authorized or hobbyist drones and misidentifications, though some cases near bases remain unresolved.", source:"FBI/DHS congressional briefing" },
  { id:"vabeachswarm", name:"Virginia Coast Navy UAP Swarm", date:"2025-05", lat:36.9, lon:-75.3, location:"Off the coast of Virginia, Atlantic Ocean", precision:"approx", status:"unresolved", agency:"U.S. Navy", summary:"Navy assets reported roughly 100 airborne UAP plus two likely uncrewed surface vessels — the only maritime case highlighted in AARO's FY2025 report.", source:"AARO FY2025 Consolidated Annual Report" },
  { id:"motherorb", name:"Western U.S. “Orbs Launching Orbs” Event", date:"2023-10", lat:39.8, lon:-108.5, location:"Undisclosed sensitive site, western United States", precision:"approx", status:"unresolved", agency:"Federal law-enforcement agents / FBI", summary:"Six agents reported an orange “mother orb” repeatedly releasing smaller red orbs with coordinated, non-ballistic motion near a sensitive site.", source:"AARO Unresolved Case Analysis Update" },
  { id:"cospringspotato", name:"Cheyenne Mountain “Potato-Shaped” Object", date:"2022-02", lat:38.74, lon:-104.85, location:"Near Cheyenne Mountain / Fort Carson, Colorado Springs, CO", precision:"approx", status:"unresolved", agency:"U.S. Army personnel / FBI", summary:"Five soldiers observed a motionless, matte-white, “potato”-shaped object with shifting, ridged panels. One low-confidence hypothesis offered was sunlight backscatter off snow.", source:"AARO case file; local news (KRDO/FOX21)" },
  { id:"cospringstriangle", name:"Colorado Springs Triangle", date:"2023-10", lat:38.86, lon:-104.76, location:"Colorado Springs, CO area", precision:"approx", status:"uncorroborated", agency:"AARO / FBI", summary:"A dark, translucent, triangular object with lights was reported over a military base in the area.", source:"AARO case file" },
  { id:"nevadadrones", name:"Nevada Nuclear Security Site Drone Incursions", date:"2023-10", lat:36.82, lon:-115.93, location:"Nevada Nuclear Security Site, near Las Vegas", precision:"exact", status:"unresolved", agency:"DOE / NNSA", summary:"Five drones overflew a Department of Energy nuclear-weapons-related site over a three-day span; the operators were never identified.", source:"DOE/NNSA incident report" },
  { id:"neorbs", name:"Northeastern U.S. Orb Sightings", date:"2024-10", lat:42.5, lon:-73.0, location:"Northeastern United States (regional)", precision:"approx", status:"unresolved", agency:"AARO / FBI", summary:"Recurring orb sightings from one area included a report of a red sphere containing a “white plasma sun.”", source:"AARO case file" },
  { id:"dccook", name:"D.C. Cook Nuclear Plant Crashed UAS", date:"2023-08-03", lat:41.97, lon:-86.56, location:"Bridgman, Michigan", precision:"exact", status:"explained", agency:"Plant security / local law enforcement", summary:"Plant security recovered a crashed unmanned aircraft system on-site; it was turned over to local police.", source:"AARO FY2023 Annual Report" },
  { id:"fewarren", name:"Nuclear Missile Field Drone Incursions", date:"2023-12", lat:41.16, lon:-104.87, location:"F.E. Warren AFB region, Wyoming", precision:"approx", status:"uncorroborated", agency:"U.S. Air Force", summary:"Formations of drones flew repeatedly over ICBM silo fields; AARO logged 18 drone sightings near U.S. nuclear infrastructure that fiscal year.", source:"AARO FY2024 Annual Report" },
  { id:"canaveralstarlink", name:"Cape Canaveral Starlink Misidentification", date:"2023-2024", lat:28.39, lon:-80.61, location:"Cape Canaveral, Florida", precision:"exact", status:"explained", agency:"Commercial airline pilot / AARO", summary:"A pilot's report of flashing lights was correlated to a Starlink satellite launch from Cape Canaveral about an hour earlier.", source:"AARO FY2024 Annual Report" },
  { id:"nycylinder", name:"Atlantic Cylindrical Object Near-Miss", date:"2023-2024", lat:40.5, lon:-72.0, location:"Off the New York coast, Atlantic Ocean", precision:"approx", status:"unresolved", agency:"Commercial airline crew / FAA", summary:"An airline crew reported a near-miss with a cylindrical object — the only case flagged as a possible flight-safety issue in AARO's FY2024 report.", source:"AARO FY2024 Annual Report" },
  { id:"vafuelcycle", name:"Virginia Fuel Cycle Facility Sightings", date:"2023-2024", lat:37.5, lon:-77.0, location:"Nuclear fuel cycle facility, Virginia (regional)", precision:"approx", status:"unresolved", agency:"DoD / DOE facility security", summary:"Six consecutive nights of UAP sightings were reported at the facility, cited by AARO as a notable pattern near critical infrastructure.", source:"AARO FY2024 Annual Report" },
  { id:"satflare", name:"Satellite Flaring Misidentification Wave", date:"2024-2025", lat:39.5, lon:-98.35, location:"United States (nationwide)", precision:"approx", status:"explained", agency:"AARO analytics", summary:"A new 3D-modeling capability let AARO attribute 238 separate reports nationwide to sunlight reflecting off low-Earth-orbit satellites.", source:"AARO FY2025 Annual Report" },
  { id:"heliorb", name:"Military Helicopter Orb Encounter", date:"2025", lat:39.0, lon:-105.0, location:"Location undisclosed, western United States (regional)", precision:"approx", status:"unresolved", agency:"U.S. military helicopter aircrew", summary:"A senior intelligence officer described an hour-long encounter with stationary, orange-white orbs and a triangular orb swarm that trailed scrambled fighter jets.", source:"AARO case file; news coverage of 2026 file release" },
  { id:"shadowed", name:"“Trailed or Shadowed” Pilot Encounters", date:"2023-2024", lat:38.0, lon:-95.0, location:"Locations undisclosed, U.S. military airspace (regional)", precision:"approx", status:"unresolved", agency:"USAF / Navy aircrews", summary:"Three separate aircrew reports of being trailed or shadowed by UAP were among 21 cases AARO flagged for deeper study in its FY2024 report.", source:"AARO FY2024 Annual Report" },
  { id:"radarmalfunction", name:"East Coast Navy Radar-Malfunction Encounter", date:"2023", lat:35.0, lon:-73.0, location:"Atlantic Coast warning area (regional)", precision:"approx", status:"explained", agency:"U.S. Navy", summary:"A pilot's radar malfunctioned while closing to within 4,000 feet of an object; AARO assessed with moderate confidence that it was a large, lighter-than-air balloon.", source:"AARO case file" }
];
